@apiurl = http://localhost:6969/users
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IkLDpHJ0aWwiLCJpYXQiOjE3NTg3MTQ0MjEsImV4cCI6MTc2MTMwNjQyMX0.C_yO-FauO12iMn6xWbmgiR6fYGSnSbz4yVfw5Sp0zRI

###

GET {{apiurl}}
Authorization: Bearer {{token}}

### Skapa ny användare

POST {{apiurl}}/register
Content-Type: application/json

{
    "username": "Bärtil",
    "password": "Secret"
}

### Login

POST {{apiurl}}/login
Content-Type: application/json

{
    "username": "Bärtil",
    "password": "Secret"
}

