@apiurl = http://localhost:6969/users

GET {{apiurl}}

###

POST {{apiurl}}
Content-Type: application/json

{
    "test": "Morjens"
}

###

PATCH {{apiurl}}
Content-Type: application/json


###

DELETE {{apiurl}}
Content-Type: application/json